#include "competitive-template.hpp"


// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
void solve(){
  long long N;
  cin >> N;
  long long M;
  cin >> M;
  long long L;
  cin >> L;
  
}
