[codestyle]
indent_type = 'space'
indent_width = 2
workspace_dir = 'C:/Users/denjo/Desktop/ABC'
lang = 'cpp'

## template_file is a file path to template code
template_file = 'C:/Users/denjo/Desktop/ABC/ac-template'

## code_generator_file is a path to .py file defining custom code generator function.
## Please check README.md for details.
code_generator_file ='C:\\Users\\denjo\\Documents\\kpr\\script\\ac-tools-generater.py'


[postprocess]
## exec_on_each_problem_dir is executed after every problem directory's creation
## with its problem directory as cwd like arc001/A
#exec_on_each_problem_dir='clang-format -i ./*.cpp'

## exec_on_contest_dir is executed once after `atcoder-tools gen`
## with the contest directory as cwd like arc001/
#exec_on_contest_dir=

[etc]
download_without_login = false
parallel_download = false
save_no_session_cache = false
in_example_format = "sample-{}.in"
out_example_format = "sample-{}.out"
